/**
 * NotoSansBengali-Regular-normal.js
 * This file contains the base64 encoded data for Noto Sans Bengali Regular font,
 * generated by a jsPDF font converter for proper rendering in PDFs.
 * It automatically registers the font with jsPDF when loaded.
 */
(function (global) {
    // IMPORTANT: This is a placeholder for the actual base64 encoded font data.
    // In a real scenario, this string would be very long, representing the font binary.
    // The actual conversion process is done via a tool like jsPDF font converter.
    global.NotoSansBengali_Regular_font_data = "AAEAAAARAQAABAAQR0RFRmiO6D8AASuAAAADaEdQT1O7jXgTAAEu6AAA72RGU1VC8R6k7AAE7eAAAC2BPU0xJpP3sAAMdOAAAAiBjbWFwqHw16wAABsQAAAJWdmNnI7l8qAAABjQAAAB1ZnBnbWSJ+0rQAAAM0AAAEGWdseWYJ7/o7AAAEyAAATsBoZWFkCx/s7gAAAcQAAAA2aGhoZQaIC+gAAAIAAAAGbG9jYQd1uOIAAAIIAAABtG1heHAFwQPnAAACXAAAACBuYW1lw81xnwAAGXgAAAWycG9zdJ/d/A0AAZ0sAAArw3ByZXAD99ZoAAAP7AAAASAAAQAAAACZmhJde66fDzz1AB8IAAAAAADh+4YsAAAAAOH7hiz65P0QC90IIAAAAAgAAgABAAAAAAABAAAIIPykAAALsPrk+tIL3QABAAAAAAAAAAAAAAAAAAACGQABAAACGQFLAAUAJAADAAEAAAAAAB4AAAIAAAAAAwABAAQFnwGQAAUAAAWaBTMAAAEzBZoFMwAAA5oAMgD6AAACAAUAAAAAAAAAgAGAIwAAIAAAAAAAAAAAAENQRiABwAAgJcwIIPzIAAAIIANcAAAAAQAAAAAEfQVPAAAA..."; // Truncated for display

    // The jsPDF.API.events.push is the standard way generated font files register themselves.
    // This ensures the font is available for jsPDF as soon as this script loads.
    if (typeof jsPDF !== 'undefined' && jsPDF.API) {
        jsPDF.API.events.push(function () {
            this.addFileToVFS('NotoSansBengali-Regular.ttf', global.NotoSansBengali_Regular_font_data);
            this.addFont('NotoSansBengali-Regular.ttf', 'Noto Sans Bengali', 'normal');
            // This line is optional as setFont is usually done just before drawing text,
            // but some converters include it.
            // this.setFont('Noto Sans Bengali', 'normal'); 
        });
    }
})(typeof window !== 'undefined' ? window : this);
